# Generated by Django 5.0.1 on 2024-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborator",
            name="employee_number",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
