# Generated by Django 5.0.1 on 2024-01-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_collaborator_employee_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("management", "Management"),
                            ("sales", "Sales"),
                            ("support", "Support"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="collaborator",
            name="role",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="crm.role"
            ),
        ),
    ]
