# Generated by Django 5.0.1 on 2024-02-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_role_alter_collaborator_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collaborator",
            options={
                "permissions": [
                    (
                        "manage_collaborators",
                        "Can create, update and delete collaborators",
                    )
                ]
            },
        ),
    ]
