# Generated by Django 5.0.1 on 2024-02-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_alter_collaborator_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.CharField(
                default="Global Business Summit 2024", max_length=255
            ),
            preserve_default=False,
        ),
    ]
