# Generated by Django 5.0.1 on 2024-02-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_alter_event_client_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={
                "permissions": [
                    (
                        "manage_contracts_creation_modification",
                        "Can create and modify contracts",
                    )
                ]
            },
        ),
    ]
